version: '3.5'
services:
  courses-user:
    platform: linux/amd64
    container_name: courses_user
    build: 
      context: ./.docker/mysql
      dockerfile: dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courses_user
    ports:
      - "3321:3306"
    volumes:
      - ./.docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql